### PR TITLE
added new rabbit and wolf images.

### PR DESCRIPTION
**Pull request by 1sra3l**
reverted to contain old SVG versions of rat/rabbit/wolf as well as new ones

Just an update to the images again.
Let me know if you like these versions better.

### CODE REVIEW

**Comment by 1sra3l** [comment]
@igorfs10 I added the type effectiveness "table" :smile: and the png in `assets/doc/` I figured that made sense to keep documentation for assets in that folder and the table is for the elements.

**Comment by 1sra3l** [comment]
`assets/doc/` is where the new files are since they document the types that assets will use.  I will need to implement the automatic checking for the chart.  Look through it and see if you see any things that might cause problems with gameplay for any specific ones.  I tried to spread things out decently and sensibly.

**Comment by 1sra3l** [comment]
I added 2 new songs, one mecha/industrial the other is funtimes, I like them both.

A really cool thing is happening with FLTK, [fltk-form](https://github.com/MoAlyousef/fltk-form)

I am in the process of integrating it into the rpgstat library.

Basically using fltk-form + rpgstat will give you a "viewer" of a struct, or a "generated" editor.  These are both returns as a "FlexBox" and the usage is really straight forward.  Enums become a drop-down box.  Mr. Alyosef was kind enough to add this feature to FLTK for me.

The means we can use serde + fltk-form to make in-game editors/viewers very easily.

**Comment by igorfs10** [comment]
@1sra3l That is awesome. MoAlyousef is making a great work with fltk, This will help a lot

**Comment by 1sra3l** [comment]
@igorfs10 Yes!  If the generic typed numbers can be implemented this way I will test it in character maker and use it with the `libre-creatures` repo to edit the "legendary" creatures as a test for editing them before moving Rust Hero "creatures" into the repo over there.

This will change `rpg-stat`, I will remove the ini files from the repo when I am finished.  I will likely drop the `legendary.rs` part, and we can just read them in.   What do you think about that?  I'd still like to include some basic creatures for random simple games, but I think the legendary.rs is pointless now.

We can use `fltk-form` to easily edit all the game things graphically!  If we give the group a solid color background and show it, it is basically a sub-window.  I have already done this with a random test game thing, so I know it is easy to trigger from a button `emit()`.

Feel free to merge this if you are ready

**Comment by igorfs10** [comment]
@1sra3l I agree. You can put the creatures in the creatures repo and suggest the repo in rpg lib.

**Comment by 1sra3l** [comment]
:+1: I will make `rpgstat` smaller!

I still like the ideas you have about small static things.  I think we should use [ez-pixmap](https://crates.io/crates/ez-pixmap) for button images.  I usually used "XPM" images for smaller FLTK programs I wrote in C++ like flpad


```xpm
/* XPM */
static const char * flpad_xpm[] = {
"16 16 4 1",
" 	c None",
".	c #000000",
"-	c #940000",
"@	c #FFFFFF",
"                ",
"     ------     ",
"   ----------   ",
"  --@@@@@@@@--  ",
" ---@@@@@@@@--  ",
" ---@......@--- ",
" ---@@@@@@@@--- ",
" ---@....@@@--- ",
" ---@@@@@@@@--- ",
" ---@......@--- ",
" ---@@@@@@@@--- ",
"  --@......@--  ",
"  --@@@@@@@@--  ",
"   ----------   ",
"     ------     ",
"                "};
```
The main difference would be to change the initialization to Rust array enclosed in `[ ]` instead of `{ }`
```rs
const PXM: &[&str] = &[
"16 16 4 1",
" 	c None",
".	c #000000",
"-	c #940000",
"@	c #FFFFFF",
"                ",
"     ------     ",
"   ----------   ",
"  --@@@@@@@@--  ",
" ---@@@@@@@@--  ",
" ---@......@--- ",
" ---@@@@@@@@--- ",
" ---@....@@@--- ",
" ---@@@@@@@@--- ",
" ---@......@--- ",
" ---@@@@@@@@--- ",
"  --@......@--  ",
"  --@@@@@@@@--  ",
"   ----------   ",
"     ------     ",
"                ",
];
```



It is easy to make the XPM on my computer 
for `assets/heros/elemental.png`
`convert ${infile}.png ${infile}.xpm` made this, though a pipe `|` through `sed` would make it `rust` :rofl: 
```c
/* XPM */
static char *elemental[] = {
/* columns rows colors chars-per-pixel */
"64 128 234 2 ",
"   c None",
".  c #3D211B",
"X  c #0E3838",
"o  c #3B2224",
"O  c #392335",
"+  c #7A0000",
"@  c #7B0806",
"#  c #791C17",
"$  c #6E1310",
"%  c #45251B",
"&  c #562C1D",
"*  c #7A2503",
"=  c #762805",
"-  c #623905",
";  c #6D340D",
":  c #55112A",
">  c #472A22",
",  c #45382F",
"<  c #4C352C",
"1  c #57392D",
"2  c #5A3B2D",
"3  c #4A3A33",
"4  c #473A30",
"5  c #4D2932",
"6  c #632822",
"7  c #6E322C",
"8  c #6E182C",
"9  c #1D5E1B",
"0  c #216C00",
"q  c #246A0D",
"w  c #2C7D02",
"e  c #277401",
"r  c #337B04",
"t  c #285D2C",
"y  c #706712",
"u  c #58473C",
"i  c #544031",
"p  c #674638",
"a  c #735439",
"s  c #726B36",
"d  c #4A5D1E",
"f  c #021D53",
"g  c #06295F",
"h  c #082E59",
"j  c #0E3158",
"k  c #273445",
"l  c #28344B",
"z  c #2B3252",
"x  c #222752",
"c  c #183265",
"v  c #0B367B",
"b  c #163476",
"n  c #102A6D",
"m  c #392E69",
"M  c #3E2C73",
"N  c #273172",
"B  c #412549",
"V  c #422659",
"C  c #43285C",
"Z  c #57355C",
"A  c #673848",
"S  c #542E66",
"D  c #432A7C",
"F  c #4C2D7D",
"G  c #422977",
"H  c #532F7A",
"J  c #5A3376",
"K  c #462C68",
"L  c #673770",
"P  c #521F46",
"I  c #314E49",
"U  c #384776",
"Y  c #327967",
"T  c #26605B",
"R  c #57514C",
"E  c #6B5849",
"W  c #755D4C",
"Q  c #665B57",
"!  c #6C5649",
"~  c #766151",
"^  c #7D6553",
"/  c #7C6955",
"(  c #7B664D",
")  c #565463",
"_  c #474F6D",
"`  c #7C4166",
"'  c #677B67",
"]  c #980B08",
"[  c #891808",
"{  c #96150C",
"}  c #881612",
"|  c #981514",
" . c #810503",
".. c #A10705",
"X. c #A40D08",
"o. c #A20906",
"O. c #A8170C",
"+. c #A3121A",
"@. c #9A3518",
"#. c #8A310F",
"$. c #B22816",
"%. c #B43719",
"&. c #B73410",
"*. c #802D26",
"=. c #833E34",
"-. c #A92F37",
";. c #9F1C2D",
":. c #CC3B02",
">. c #C13F0B",
",. c #894B08",
"<. c #985405",
"1. c #AD5F00",
"2. c #A35A02",
"3. c #BA491B",
"4. c #AD6000",
"5. c #854B3F",
"6. c #8A4B33",
"7. c #954E2F",
"8. c #A65123",
"9. c #AB5225",
"0. c #B95927",
"q. c #A75937",
"w. c #AB4722",
"e. c #937130",
"r. c #B27531",
"t. c #836314",
"y. c #C8410B",
"u. c #C44512",
"i. c #D14912",
"p. c #C95827",
"a. c #CA5E30",
"s. c #D96927",
"d. c #C86235",
"f. c #D26A2F",
"g. c #F37329",
"h. c #E46D31",
"j. c #EA6F2B",
"k. c #B9255A",
"l. c #A3305D",
"z. c #A63B6C",
"x. c #954B58",
"c. c #895747",
"v. c #AD4243",
"b. c #BC5B45",
"n. c #AA4F4C",
"m. c #996549",
"M. c #856C5A",
"N. c #856856",
"B. c #8A715E",
"V. c #8D6B48",
"C. c #834462",
"Z. c #A96A57",
"A. c #C05D44",
"S. c #D1624A",
"D. c #E37643",
"F. c #E66355",
"G. c #F57165",
"H. c #2F8102",
"J. c #338503",
"K. c #368B04",
"L. c #398E04",
"P. c #37830B",
"I. c #3A9104",
"U. c #44890E",
"Y. c #6F8518",
"T. c #578425",
"R. c #4E8836",
"E. c #6D8234",
"W. c #66B12C",
"Q. c #62A12C",
"!. c #7EC03E",
"~. c #26826F",
"^. c #6BAC54",
"/. c #51916F",
"(. c #5FA07E",
"). c #5C9F4E",
"_. c #A79632",
"`. c #CA8716",
"'. c #C9861C",
"]. c #CB8919",
"[. c #D48E15",
"{. c #CA843C",
"}. c #C28620",
"|. c #E49D36",
" X c #918D54",
".X c #92AF78",
"XX c #DE9447",
"oX c #E98454",
"OX c #E3AB51",
"+X c #DEA950",
"@X c #8FCF50",
"#X c #F5C34E",
"$X c #FBD967",
"%X c #FFE16A",
"&X c #052E8C",
"*X c #092C89",
"=X c #1C2C8D",
"-X c #102D8D",
";X c #093385",
":X c #18358C",
">X c #032E95",
",X c #0B2D95",
"<X c #002E99",
"1X c #132D92",
"2X c #1A2C91",
"3X c #03349C",
"4X c #0C3A95",
"5X c #252B8C",
"6X c #312F86",
"7X c #063DA7",
"8X c #452981",
"9X c #482A80",
"0X c #294C82",
"qX c #367899",
"wX c #366C85",
"eX c #0A44A9",
"rX c #1549A8",
"tX c #0A49B5",
"yX c #0D52BE",
"uX c #1559B8",
"iX c #1D61B0",
"pX c #2A6EA6",
"aX c #114489",
"sX c #407C88",
"dX c #A45BBB",
"fX c #A56DE2",
"gX c #0E9A83",
"hX c #3D8190",
"jX c #458686",
"kX c #53B297",
"lX c #43D4B4",
"zX c #FD9492",
"xX c #FBA898",
"cX c #FEA9A2",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                      ..                                                        ",
"                                                                    ..        o.                                                ",
"                                                                    ..      ..                                                  ",
"                                                                  ..      ..                                                    ",
"                                                                  ..    ....                                                    ",
"                                                                  ..    ..                                                      ",
"                                                                  ..    ..                                                      ",
"                                                      + + +       ..    ..          + + + +                                     ",
"                                                + + + + + + +     o.              + + + + + + + +                               ",
"                                            + + + + + + + + + +               + + + + + + + + + + +                             ",
"                                          + + + + + + + + + + + +             + + + + + + + + + + + +                           ",
"                                          + + + + + + + + + + @ w.OX$X$X%X$X{.r.@.+ + + + + + + + + +                           ",
"                                        + + + + + + + + + + @.+Xd.%.O.X.X.$.d.XX#X+X[ + + + + + + + +                           ",
"                                        + + + + + + + + + 9.OXO...................p.OX@ + + + + + + + +                         ",
"                                      + + + + + + + + + @.XXX.......................$.9.+ + + + + + + +                         ",
"                                      + + + + + + + + @ +XX...........................3.+ + + + + + + +                         ",
"                                      + + + + + + + + w.$.................o.o.........X. .+ + + + + + +                         ",
"                                      + + + + + + + + 0.o...o.o.............] o.........[ + + + + + + +                         ",
"                                      + + + + + + + + %.o.....o...] } ....o.# o.......o.{ + + + + + + +                         ",
"                                      + + + + + + + + X.o.| c.o...} # ....{ 6 ..........{ + + + + + + +                         ",
"                                        + + + + + + ] X.7.kXlX} ..} p ] ..} < ....o.dX+.{ + + + + + + +                         ",
"              :.:.                      + + + + + +  .{..XkXkXu { ] / # ..] , } ..+.fXz.] + + + + + +                           ",
"          :.y.D.oXD.y.            B.B.B.c.5.5.5.5.5.5.m.Z.e.e.a < # c.u } ..6 6 ..| l.n.| *.*.*.*.*.=.                          ",
"          D.cXcXcXcXA.                N.~ E E ~ / B.B.B. X@X@XE., , 3 N.i < & , } %.|.{.N.B.B.M./ ~ E E ~ N.B.                  ",
"        s.cXzXzXG.F.-.a.                  N.W E u 4 3 ~  X_._.s , , u B.M.R , , i s.#X|.B./ 3 4 u E / B.                        ",
"        oXxXF.;.;.-.v.i.                        B.M.~ ! ' Y ~.I W ~ B.B.B.B.N.W 4 f.f.r.B.E W M.B.                              ",
"        i.xXv.v.v.n.p.:.                              c.' gXgXT s T.T.T.T.T.T.T.d k.k.k.B.B.B.                                  ",
"        :.:.p.a.p.:.:.:.                              @ / R p d K.I.I.I.I.I.I.J.0 k.k.k.B.                                      ",
"        :.:.:.:.:.:.:.:.                            + $ r Y.Y.Y.e H.w K.L.K.I.I.J.@.$.#.P.                                      ",
"        :.:.:.:.:.:.:.                              + U.e W.W.Q.0 0 0 0 e e H.I.P.g.g.s.L.                                      ",
"        :.:.:.:.:.:.:.                                w 0 y t.y 0 0 w L.I.I.I.I.r g.g.s.J.                                      ",
"        :.:.:.:.:.:.                              b w w 0 [ ..= 0 e w J.J.K.L.I.K.* ..- K.T ,X                                  ",
"        :.:.:.:.:.                            =X>X&Xe 0 0 * ..= 0 e J.L.I.I.L.H.e * ..- I.t <X<X1X                              ",
"        :.:.:.:.:.                          1X<X<X<Xt 0 0 = ..* 0 0 0 0 e w J.w 0 * ..- P.;X<X<X<X,X                            ",
"        :.:.:.:.:.                          tX3X<X<X<X9 0 = ..[ L.I.I.I.I.K.w J.J.= ..- f >X<X3X7XtX                            ",
"        :.:.:.:.:.                        rXyXyXeX3X<X&XX ; ..[ w I.I.I.I.I.L.J.P.= ..: g 7XtXyXiX(.                            ",
"        :.:.:.:.:.                        rXyXqXyXyXtXtX3X: ..[ 0 q q q q q 9 X f $ ..P yXuXyXyXpXU.Y                           ",
"        :.:.:.:.:.                        rX).^.yXyXiXpXyXZ ..] g h h h g g g g g 8 ..S pX^.iXyXqX^.0X                          ",
"        :.:.:.:.:.                        wX).!.uXuXQ./.yXS ..| ;Xg g h I g g g aX7...S hXP.@XrX3X<X,X                          ",
"        :.:.:.:.:.                        <X<X4XeXjXQ.@XyXS ] { uXtX;XI 9 j v tXjX; { S qXwX3X<X<X<X,X                          ",
"        :.:.:.:.:.                      -X<X<X<X<X<X<X4X7XA a s qXtXuX^.R./.tXtXsXQ Z N <X<X<X<X<X<X,X                          ",
"        :.:.:.:.:.                      >X<X<X<X<X<X<X<X<X,X,X>X<X<X;X;X<X<X<X<X<X>X>X<X<X<X<X<X<X<X>X                          ",
"        :.:.:.:.:.                    ,X<X<X<X<X<X<X<X<X<X<X<X<X<X>Xk l <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                          ",
"          :.:.:.:.                    ,X<X<X<X<X<X<X<X<X<X<X<X<X<Xb k l <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                          ",
"          :.:.:.:.                    <X<X<X<X<X<X<X<X<X<X<X<X<X<Xl k l <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                          ",
"          :.:.:.:.                    <X<X<X<X<X<X<X<X<X<X<X<X<Xb k k l <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                        ",
"          :.:.:.:.                  ,X<X<X<X<X<X<X<X<X<X<X<X>Xc k k k k <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                        ",
"          :.:.:.:.                  ,X<X<X<X<X<X<X<X<X&Xv c l k k k k k <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                        ",
"          :.:.:.:.                  =Xc c c c N 6X6XD k k k k k k k k k >X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                        ",
"          :.:.:.:.                  m k k k k M 8X8XG k k k k k k k k k >X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                        ",
"          :.:.:.:.                z k k k k z 8X8X8XG k k k k k k k k k >X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                        ",
"          :.:.:.:.                k k k k k m 8X8X8XM k k k k k k k k k >X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X=X                      ",
"          :.:.:.:.              k k k k k l D 8X8X8XM k k k k k k k k k &X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                      ",
"          :.:.:.:.            k k k k k l G 8X8X8X8XM k k k k k k k k k &X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                      ",
"          :.:.:.:.          k k k k k z G 8X8X8X8X8Xm k k k k k k k k k &X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                      ",
"          :.:.:.:.        k k k k k z D 8X8X8X8X8X8Xm k k k k k k k k k *X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                      ",
"            :.:.u.      k k k k k z D 8X8X8X8X8X8X8Xm k k k k k k k k k ;X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                      ",
"            3.m.B.B.B.M.k k k k z D 8X8X8X8X8X8XH C.K k k k k k k k k k ;X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X                    ",
"          3.B.q.3.N.B.B.R k k k 8X8X8X8X8X8X8XF f.g.5.k k k k k k k e.e.N <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                    ",
"          q.q.u.u.B.W N.~ k k   8X8X8X8X8X8X8Xx.g.0.p 3 3 3 3 3 3 3 [.[._ <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                    ",
"          m.m.3.y.B.M.M.B.Q     8X8X8X8X8X8XH h.g.7.1 1 1 1 1 1 1 2 [.[._ <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X>X                    ",
"          m.B.q.>.N.B.^         8X8X8X8X8X8XA.g.g.7.1 1 1 1 1 1 1 2 [.[.) <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                    ",
"          q.3.:.>.! ^           8X8X8X8X8XJ g.f.n.6.1 1 1 1 1 1 1 1 [.[.) <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                    ",
"          m.u.:.&.              8X8X8X8X8XF x.H 8XA 1 1 1 1 1 1 1 1 [.[.) <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X                  ",
"            :.:.:.            8X8X8X8X8X8X8X8X8X` f.2 > > > > > > > `.[.Q <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                  ",
"            :.:.:.            8X8X8X8X8X8X8XF n.g.g.6 . . . . . . . `.[.Q <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                  ",
"            :.:.:.            8X8X8X8X8X8XF A.g.g.g.& . . . . . . . `.[.Q <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                  ",
"            :.:.:.            8X8X8X8X8X8Xb.g.g.g.g.& . . . . . . . `.[.~ <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                  ",
"            :.:.:.            8X8X8X8X8Xx.g.g.g.g.g.% . . . . . . . `.[.( <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X                ",
"            :.:.:.          8X8X8X8X8XJ j.g.g.g.g.g.% . . . . . . . `.[.( <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X                ",
"            :.:.:.          8X8X8X8X8Xb.g.g.g.g.g.g.. . . . . . . . `.[.V.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X                ",
"            :.:.:.          8X8X8X8XL g.g.g.g.g.g.j.. . . . . . . . `.[.V.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X                ",
"            :.:.:.          8X8X8X8XA.g.g.g.g.g.g.s.. . . . . . . . `.[.e.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                ",
"            :.:.:.          8X8X8XJ g.g.g.g.g.g.g.s.. . . . . . . . `.[.e.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                ",
"            :.:.:.        8X8X8X8Xn.g.g.g.g.g.g.g.a.. . . . . . . . `.[.r.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X                ",
"            :.:.:.        8X8X8X8Xh.g.g.g.g.g.g.g.p.. . . . . . . . `.[.r.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X              ",
"            :.:.:.        8X8X8XL g.g.g.g.g.g.g.g.0.. . . . . . . . '.[.r.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X              ",
"            :.:.:.        8X8X8Xx.g.g.g.g.g.g.g.g.0.. . . . . . . . '.[.}.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X              ",
"            :.:.:.        8X8X8Xn.g.g.g.g.g.g.g.g.9.. . . . . . . . '.[.}.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X>X              ",
"            :.:.:.      8X8X8X8Xx.g.g.g.g.g.g.g.g.8.. . . . . . . . '.[.'.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X              ",
"            :.:.:.      8X8X8X8XC.g.g.g.g.g.g.g.g.8.. . . . . . . . '.[.[.<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X              ",
"            :.:.:.      8X8X8X8XJ g.g.g.g.g.g.g.g.8.. . . . . . . . '.[.[.>X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X=X            ",
"            :.:.:.      8X8X8X8X8Xd.g.g.g.g.g.g.g.8.. . . . . . . o '.[.[.,X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X            ",
"            :.:.:.      8X8X8X8X8X` g.g.g.g.g.g.g.8.. . . . . . . O '.[.[.:X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X            ",
"            :.:.:.      8X8X8X8X8X8Xb.g.g.g.g.g.g.8.. . . . . . . B '.[.[.:X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1X            ",
"            :.:.:.    8X8X8X8X8X8X8XJ h.g.g.g.g.g.8.. . . . . . . B '.[.[.:X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X            ",
"            :.:.:.    8X8X8X8X8X8X8X8XJ h.g.g.g.g.8.. . . . . . . C '.[.[.0X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X>X            ",
"            :.:.:.    8X8X8X8X8X8X8X8X8XH n.h.g.h.7 . . . . . . . K '.[.[.U <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X            ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8XD H 9XV . . . . . . . D '.[.[.U <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X            ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . o 8X'.[.[.U <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X            ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . O 8XH F J =X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X            ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . 5 8X8X8X8X2X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X=X          ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . B 8X8X8X8X2X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X          ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . V 8X8X8X8X=X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X2X          ",
"            :.:.:.    8X8X8X8X8X8X8X8X8X8X8X8X8X8XV . . . . . . K 8X8X8X8X5X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X,X1X2X            ",
"              :.:.            8X8X8X8X8X8X8X8X8X8XV . . . . . . G 8X8X8X8X5X<X<X<X<X<X<X<X<X<X<X<X<X,X2X5X5X                    ",
"              :.:.                        8X8X8X8XC ; ,.<.<.; % 8X8X8X8X8X5X<X<X<X<X<X<X&Xn b 5X6X                              ",
"              :.:.                                1.1.1.1.1.1.1.a 8X8X8X8X5X>X*Xn x O o . % %                                   ",
"              :.:.                                1.1.1.1.1.1.1.1.            ,.,.<.2.2.1.1.                                    ",
"              :.:.                                1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.1.                                    ",
"              :.:.                                1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.1.                                    ",
"              :.:.                                1.1.1.1.1.1.1.1.          4.1.1.1.1.1.1.1.                                    ",
"              :.:.                                1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.                                      ",
"              :.:.                                1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.                                      ",
"              :.:.                            1.1.1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.                                      ",
"              :.:.                          1.1.1.1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.1.1.1.1.                              ",
"              :.:.                        1.1.1.1.1.1.1.1.1.1.1.1.          1.1.1.1.1.1.1.1.1.1.1.1.1.                          ",
"              :.:.                      1.1.1.1.1.1.1.1.1.1.1.1.1.          4.1.1.1.1.1.1.1.1.1.1.1.1.                          ",
"              :.:.                      1.1.1.1.1.1.1.1.1.1.1.1.1.            1.1.1.1.1.1.1.1.1.1.1.1.                          ",
"              :.:.                      1.1.1.1.1.1.1.1.1.1.1.1.                1.1.1.1.1.1.1.1.1.1.1.                          ",
"                                        1.1.1.1.1.1.1.1.1.1.1.                    1.1.1.1.1.1.1.1.1.1.                          ",
"                                              1.4.1.                                    1.1.1.1.1.1.                            ",
"                                                                                                                                "
};

```

**Pull request merged**
