### PR TITLE
removed obsolete Piskel file, cleaned up desert song file added LICENSE and README.md for assets

### PR DESCRIPTION
**Pull request by 1sra3l**
That says it all.  I figured I should add the legal stuff so it would not be under copyright to me only :smile:   This way anyone can use the art as long as they say where it is from and are not trying to make commercial games with it!  Free for other free games!

Same thing with the music.  People can modify the files and make long versions, or whatever just to get started, as long as they are not trying to make money :smiley_cat: 

This will allow others to know they can use it legally in other libre software projects if they ever want to!

### CODE REVIEW

**Comment by 1sra3l** [comment]
@igorfs10 P.S. have you listened to any of the loop files?  I use the program Audacious (similar concept to the old WinAmp style player) to listen to loops easily.  Just make a playlist for each file, set it on loop and see if it annoys you.  If there is one you don't like please let me know so I can make it not annoying for others :laughing:

**Comment by 1sra3l** [comment]
@igorfs10 One other p.s.  :rofl: 

I am thinking about layering various textures over the art to give it a more "analog" feel.  I am thinking things like fabric textures, and paper.  I'll make some examples soon, when I work on some other characters.  Because I am thinking about making more "Heros" I was thinking it would be wise for a hero traveling the globe to have a mask, so do you mind if I give all the characters a mask, though for most it will look like a scarf of sorts.
Let me know what you think!

**Comment by igorfs10** [comment]
> @igorfs10 P.S. have you listened to any of the loop files? I use the program Audacious (similar concept to the old WinAmp style player) to listen to loops easily. Just make a playlist for each file, set it on loop and see if it annoys you. If there is one you don't like please let me know so I can make it not annoying for others 😆

Yes, I forgot to comment about loop files😅, I really liked them, I let it play for some minutes and no problem for me. I just think it will sound better in a game with a dark feeling something like Final Fantasy VI or Metroid but let see how it will sound in game to be sure, otherwise we can do some small change to art to use dark colors. I like the texture idea, I think they fit they will fit with the loops style, and yeah, as he will travel to different places I completely agree with the mask. 👍

**Comment by 1sra3l** [comment]
Yeah I guess times have been a bit dark lately, I guess it unavoidably shows up in the music.  I'll try to go for happier music in the future to keep the game light hearted.  The desert song is about how it feels to live in the US sometimes :smile:

Glad you like the mask idea :mask:

**Comment by igorfs10** [comment]
> Yeah I guess times have been a bit dark lately, I guess it unavoidably shows up in the music. I'll try to go for happier music in the future to keep the game light hearted. The desert song is about how it feels to live in the US sometimes 😄
> 
> Glad you like the mask idea 😷

I agree, these times are hard, and corona is making them worse. I really liked the music, my favorite games have something darker, Super Metroid, Final Fantasy VI, Hollow Knight, they bring me some deeply feelings that makes them more me tense and let me focus until the ends. To be honest, I think that we can change some other things, like desert background that are too colorful for the song, maybe it just needs a darker color style. Wow, I don’t know if is the same for you, but I feel something angsty and a heavy feeling that I don’t know how to describe with desert music. I hope everything is okay.

**Comment by 1sra3l** [comment]
:+1:  to Super Metroid and Final Fantasy.  I haven't played Hollow Knight.  Honestly I am a pretty big fan of the old JRPGs like Chrono Trigger, and Secret of Mana, I still replay those games every so often.

The angst and heaviness are real, and something I have been working through.  Basically a lot of people have lost their perception of reality here.  A lot of people are fully convinced of lies.  Most of my family is that way.  I have probably lost my mom to lies forever.  And that is just the "commit friendly" stuff.  Good news is that I am still alive, I have a home, I have food and water!  I am also coming to grips with these people being gone forever, though still hoping one day they will snap out of it.

Hope things are better there, at least we have vaccines and masks :grin:

**Comment by igorfs10** [comment]
> 👍 to Super Metroid and Final Fantasy. I haven't played Hollow Knight. Honestly I am a pretty big fan of the old JRPGs like Chrono Trigger, and Secret of Mana, I still replay those games every so often.

I feel sorry. I don’t know if it’s happening in US but there are a lot of things happening in my country about politics and fake news, because of that, people are separating themselves with their politics choices and a lot of lies, now appears that everything is related to that, even a disease is used for that. I don’t know if it’s related, but that is what come to my mind when someone talk about a lot of peoples and lies. I hate to talk about everything about politics, so the best that I can do is to avoid talking about that, it’s hard because even some people of my family like to talk about that, so I just agree and try to talk about another subject. For these times where we need to stay home, I prefer to talk with my friends online, there is no politic, just a talk about games and music. I suggest talking with friends about what you like, it’s helping me. 😀 

Chrono trigger is my favorite game, I made all endings with every variation like destroying epoch and not reviving Crono. Secret of Mana is a great game, I played a lot, but I never finished, always happen something that makes me stop playing, I stopped right after Popoi joins the party, I guess there is a lot of things after that. I think I will play again and try to finish this time.😀

**Comment by 1sra3l** [comment]
@igorfs10 I am with on Chrono Trigger.  I have played `New Game +` a whole bunch.  I actually own the Japanese cartridge, and have a Retrode I copied it off of.  So I play Chrono Trigger in Japanese most of the time now.  The only real difference is when you save Lucca's Mom, instead of `L+A+R+A` it is `L+A+L+A` because Japanese has no "L".  Glad we have the same favorite game!
Secret of Mana originally was going to include many ideas that ended up in Chrono Trigger.  Games had very strict size limits, so they ended up making Chrono Trigger since they couldn't fit everything in one game.

Yeah most of the weird stuff is the political stuff, it is lame.  Talking with you about video games and music is definitely nice.  This project is really one of those things I am doing to help.  Thanks for letting me participate!

**Comment by 1sra3l** [comment]
@igorfs10 If you want to ever make a Libre Super Mertroid clone, I can make some music and art for you :smile:

**Comment by igorfs10** [comment]
@1sra3l Cool. I never found Chrono Trigger for snes here, I found Secret of Mana, but I was a child and didn’t understand English, so I had to emulate both games with a fan translation, the translations were bad but at least I could understand. I bought the ds version later, that time I played in English, sadly I lost, and I don’t know why but the ds usa version is extremely expensive nowadays here.
I love Super Metroid, but I don’t have time now for Rust Hero which is much simpler, Metroid will take much more. I want to make one day because I want to figure out how some mechanics and physics works, but it so much work for now. 😅

**Comment by 1sra3l** [comment]
I bought the cartridge online and used my device to copy it to play on the computer!  It would be nice if Nintendo rewrote their games to be cross platform and make something like steam but for Nintendo games, that would make it much easier to get obscure titles.  The Sega Games on steam are ROM files that you can play in retroarch, and there are some nice jRPGs in there you might like.  See if you can get it on sale!  I also highly suggest simply copying the roms over to use in retroarch, it is a really good emulator.  They also host some cool game jam-type roms too.

I agree that Rust Hero is much simpler, and that is why I felt good about joining in with you!

Oh, I have been wondering about using an ECS  (Entity Component System), have you thought about that at all?

**Comment by igorfs10** [comment]
I will look at sega collection, I don't played Genesis too much, I had snes at time.

Yes, I was planning to use Bevy engine, mostly because I wanted a mobile version, but ecs appear to be complex to learn for a simple game, at least Bevy's ecs, I still want to learn it, maybe I use it in a future project.

**Comment by 1sra3l** [comment]
It has Phantasy Star which is kinda neat RPG collection and some Sonic Games which are pretty fun platformers, as well as a bunch of other fun games.  I bought it on steam for around $7 USD, so it was not much for 50 something video games.

FLTK works on Android, have you seen [his repo](https://github.com/fltk-rs/fltk-rs-android)?
Not on a Pinephone (unless you use X11 for now, though 1.4 is around the corner... who knows), or iOS though.  But iOS costs too much for a free game like this I'd think.  Google is much more affordable for that kind of thing!  Do you already have an apple thing?  I don't, I have a Google one, and haven't updated any apps for a long time there.  I wrote those in haXe, which is like Rust, but not as good overall in the current day and age.  WASM is more than good enough in Rust so everything is basically good enough compared.  With FLTK the ecosystem in Rust is good enough for me to do tons of things.

**Comment by 1sra3l** [comment]
There are also toolkit independent ECS crates

**Comment by igorfs10** [comment]
That is great. I didn't know fltk runs on android, I was planning to use another toolkit to port to android, that's the main reason I created a crate to put the game logic and another crate for the toolkit. I dont have Apple devices, it's too expensive and closed imo. I like to install apps outside store without doing a lot of hacking and I like to install custom roms, so no apple. I will take a better look at ecs and how to use it in the game.

**Comment by 1sra3l** [comment]
Absolutely!  FLTK is pretty cool!  I morally disagree with Apple so I don't use their products, and I do not use the BSD operating system either.  I run only the Linux kernel on things.  My phone is actually neither Android, not Apple.  Have you heard of the Pinephone?  It is still limited (No MMS yet...) and it is mostly for nerds (like us) so you might check it out.  There is a really cool amount of hardware modification you can do!

**Comment by igorfs10** [comment]
Yeah, I heard of Pinephone, I’m very curious about other mobile os, sadly it will be too expensive to import the phone for my usage, I use android a lot for games and some apps nowadays, so it will be my main os for now, but I almost used firefox os as my main os some years ago with Xperia U, the only issue I had was storage that it doesn’t recognize a partition that emulate a sd card, it was so fast on Xperia U, sadly they stopped development. I'm waiting for someone to port ubuntu touch for one of my old phones, I really want to try it.

**Comment by 1sra3l** [comment]
Sorry it is too expensive to import there.  It is a decently cheap dev phone for messing around, and makes calls/texts.  Github is the closest I get to social media, so it is plenty for me.  Especially since I am making my own things for it, I worked on a small distro a while ago and I want to port things using Rust.  Ubuntu touch is really nice to use, but uses an older Kernel, I am waiting for the newest release for the Pinephone to try it out.  Rust Hero should work on it, though FLTK 1.3.X uses X11 for the backend, I think 1.4 series will address this by separating the rendering backends.
On another note things in my life have gotten much better, so if you want a happier song I think I am in a place to make happier songs :grin: We can save the desert song for the Metroid clone.  Have you played "Metroid the Other M" it does a nice job of bridging the 2D/3D gap without sacrificing much to gameplay.  I like a lot of the adaptations for the Super Metroid gameplay mechanics.

**Pull request merged**
